# Generated by Django 4.1.3 on 2022-12-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='uuid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
