# Generated by Django 4.1.3 on 2022-12-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_score_time_score_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
