# Generated by Django 4.1.3 on 2022-11-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0002_rename_user_score_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='player',
        ),
        migrations.AddField(
            model_name='score',
            name='player_id',
            field=models.CharField(default='default_id', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='submitted_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
