# Generated by Django 4.1.3 on 2022-11-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_remove_score_player_score_player_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='private_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='public_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='player_id',
            field=models.CharField(max_length=50),
        ),
    ]
