# Generated by Django 4.1.3 on 2022-11-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0004_alter_leaderboard_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='extra',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
