# Generated by Django 4.1.3 on 2023-03-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
    ]
