# Generated by Django 4.1.3 on 2022-11-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0005_score_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='submitted_date',
            field=models.DateTimeField(),
        ),
    ]
