# Generated by Django 4.1.3 on 2022-11-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0006_alter_score_submitted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='player_id',
        ),
    ]
